In [20]:
import pandas as pd

df = pd.read_parquet("/mnt/d/projects/recoscale/data/export_data/item_features")
df = df.sort_values("item_idx").reset_index(drop=True)
df.head()

,parent_asin,title,price,average_rating,rating_number,main_category,store_encoded,item_idx
0,B001UHMUXC,Casio Women's LW200-7AV Digital Watch with Whi...,19.420000,4.4,1721,0,102,0
1,B0BRX8TCWS,Amazon Essentials Men's Full-Zip Hooded Fleece...,23.120001,4.5,43896,0,21,1
2,B0C55V2Y3Q,Custer's Night High Waist Out Pocket Yoga Shor...,19.990000,4.4,13949,0,63295,2
3,B09SGTVP68,Sexy Basics Women's Active Sport Thong Panties...,36.990002,3.9,6133,0,2881,3
4,B07X1G5PBB,Ezi Satin Nightgowns for Women - Soft & Breath...,22.990000,4.5,1334,0,2299,4

In [21]:
df = df.drop(['store_encoded', 'parent_asin', 'title'], axis= 1)
df.head()

       price  average_rating  rating_number  main_category  item_idx
0  19.420000             4.4           1721              0         0
1  23.120001             4.5          43896              0         1
2  19.990000             4.4          13949              0         2
3  36.990002             3.9           6133              0         3
4  22.990000             4.5           1334              0         4